import numpy as np
import pandas as pd
from datetime import datetime
from pathlib import Path
import re

def prep_for_aldex2(adata, curr_dir, savestr, savestr2= None, obs_key= 'cell_type', count_layer= 'raw_counts'):
    """
    Prepare MERFISH data for ALDEx2 differential gene expression modeling.

    Args:
        adata (Anndata object): Adata to be modeled.
        curr_dir (str): Directory to save csv files.
        savestr (str): First part of csv filename.
        savestr2 (str, optional): Second part of csv filename. Defaults to None, assigned current date in function.
        obs_key (str, optional): Anndata.obs key that denotes cell grouping to subset. Defaults to 'cell_type'.
        count_layer (str, optional): Layer where raw transcript counts are stored. Defaults to 'raw_counts'.
    """

    if savestr2== None:
        savestr2= datetime.today().strftime("%m%d%Y")
    for cell_type in np.unique(adata.obs[obs_key]):
        adata_subset = adata[adata.obs[obs_key] == cell_type].copy()
        if count_layer:
            adata_df = pd.DataFrame(adata_subset.layers[count_layer], columns= adata_subset.var_names, index= adata_subset.obs.index ).T
        else:
            adata_df= adata_subset.to_df().T
        nt_str= re.sub(r"[ /]", "_", cell_type).lower()
        output_dir = Path(curr_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        adata_df.to_csv(output_dir / f"{savestr}_{nt_str}_{savestr2}.csv")
        adata_md= adata_subset.obs
        adata_md.to_excel(output_dir / f"{savestr}_{nt_str}_md_{savestr2}.xlsx")
        del adata_subset, adata_df, adata_md

def postprocess_aldex2(
    aldex_results,
    curr_dir=None,
    s1=None,
    s2=None,
    savestr=None,
    exp_col=None,
    savestr2=None,
    significant=True,
    gene_info=False,
    pivot=True,
    p_thresh=0.05,
    signed=False,
    **kwargs,
):
    """
    Post-process ALDEx2 differential gene expression results. Filters significant different genes between experimental conditions for each cell types. Optionally also adds information about genes, and produces pivot table summarizing genes that came up in multiple cell types.

    Args:
        aldex_results (list of str):  A list of file path generated by glob.
        curr_dir (str): Directory to save csv files.
        s1 (str): First part of common string in aldex result files. E.g. 'neuron_subset_'
        s2 (str): Second part of common string in aldex result files. E.g. '_results_111424'
        savestr (str): Filename for postprocessing results.
        exp_col (str): Experimental condition identifier in aldex results. E.g. 'age_binary'.
        savestr2 (str): Filename for pivot table. Pass '' if pivot= False.
        significant (bool): Whether to retain only significant results. Defaults to True.
        gene_info (bool, str, dict or pd.DataFrame, optional): Whether to include gene information. Defaults to False.
        pivot (bool, optional): Whether to include pivot table as a separate file. Defaults to True.
        p_thresh (float, optional): Adjusted p-value threshold. Defaults to 0.05.
        signed (bool, optional): Whether pivot table should include info about directionality of effect sizes. Defaults to False.
    """
    # Support the explicit keyword names used by the cleaned notebooks while
    # retaining compatibility with the historical kimlabspatial interface.
    aliases = {
        "output_dir": "curr_dir",
        "filename_prefix": "s1",
        "filename_suffix": "s2",
        "output_stem": "savestr",
        "experimental_column": "exp_col",
        "pivot_filename": "savestr2",
        "make_pivot": "pivot",
    }
    values = {
        "curr_dir": curr_dir,
        "s1": s1,
        "s2": s2,
        "savestr": savestr,
        "exp_col": exp_col,
        "savestr2": savestr2,
        "pivot": pivot,
    }
    for explicit_name, historical_name in aliases.items():
        if explicit_name in kwargs:
            values[historical_name] = kwargs.pop(explicit_name)
    if kwargs:
        raise TypeError(f"Unexpected keyword arguments: {sorted(kwargs)}")

    curr_dir = values["curr_dir"]
    s1 = values["s1"]
    s2 = values["s2"]
    savestr = values["savestr"]
    exp_col = values["exp_col"]
    savestr2 = values["savestr2"]
    pivot = values["pivot"]
    required = {"curr_dir": curr_dir, "s1": s1, "s2": s2,
                "savestr": savestr, "exp_col": exp_col}
    missing = [name for name, value in required.items() if value is None]
    if missing:
        raise TypeError(f"Missing required arguments: {missing}")

    output_dir = Path(curr_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if gene_info:
        if isinstance(gene_info, str) or isinstance(gene_info, pd.DataFrame):
            from kimlabspatial.preprocessing import extract_gene_info
            gene_info = extract_gene_info(gene_info)

    cell_types= []
    for aldex_result in aldex_results:
        result_path = str(aldex_result)
        idx1 = result_path.find(str(s1)) + len(str(s1))
        idx2 = result_path.find(str(s2), idx1)
        if idx1 < len(str(s1)) or idx2 < 0:
            raise ValueError(f"Could not parse stratum label from {result_path}")
        cell_type = result_path[idx1:idx2]
        cell_types.append(cell_type)

    results={cell_type: None for cell_type in cell_types}

    j=0
    for aldex_result in aldex_results:
        print(aldex_result)
        result_df= pd.read_excel(aldex_result, engine='openpyxl' )
        #result_df.rename(columns= {' ': 'Gene'}, inplace=True)
        if significant== True:
            sig_result_df= result_df[result_df[f"{exp_col}:pval.adj"]<= p_thresh]
        else:
            sig_result_df= result_df
        sig_genes= sig_result_df['gene'].values
        if gene_info and isinstance(gene_info, dict):
            this_gi= ['' for _ in range(len(sig_genes))]
            for i, sig_gene in enumerate(sig_genes):
                sig_gene= sig_gene.capitalize()
                if sig_gene in gene_info.keys():
                    for item in gene_info[sig_gene]:
                        this_gi[i]+= item
                        this_gi[i]+= ', '
            pos1= sig_result_df.columns.get_loc('gene')
            sig_result_df.insert(pos1+1, 'Gene_info', this_gi)
        results[cell_types[j]]= sig_result_df
        j+=1

    writer = pd.ExcelWriter(output_dir / f"{savestr}.xlsx")
    for key, value in results.items():
        value.to_excel(writer, sheet_name=key)
    writer.close()

    if pivot:
        combined_genes= pd.concat(pd.DataFrame(results[result]['gene']) for result in results)
        #print(combined_genes)
        # combined_genes = combined_genes.reset_index(drop=True)
        gene_counts= combined_genes.value_counts().reset_index()
        gene_counts.set_index('gene', inplace=True)
        gene_counts.index.name=None
        for name, df in results.items():
            if signed:
                df.set_index('gene', inplace=True)
                est_map = df[f"age_binary:est"]
                gene_counts[name] = gene_counts.index.map(
                    lambda g: (
                        "+" if g in est_map.index and est_map.loc[g] > 0
                        else "-" if g in est_map.index and est_map.loc[g] < 0
                        else 0
                    )
                )

            else:
                gene_counts[name] = gene_counts.index.isin(df.index).astype(int)
        if signed:
            positive_counts = gene_counts.iloc[:, 1:].eq("+").sum(axis=1)
            negative_counts = gene_counts.iloc[:, 1:].eq("-").sum(axis=1)

            count_idx = gene_counts.columns.get_loc("count")
            gene_counts.insert(count_idx + 1, "positive", positive_counts)
            gene_counts.insert(count_idx + 2, "negative", negative_counts)
            total_signs = gene_counts["positive"] + gene_counts["negative"]

            gene_counts.insert(count_idx + 3, "sign_agreement", (gene_counts[["positive","negative"]].max(axis=1) / total_signs * 100).fillna(0))
        if not savestr2:
            raise ValueError("A pivot filename is required when pivot=True")
        gene_counts.to_excel(output_dir / savestr2)
