import scanpy as sc
import numpy as np
import pandas as pd
try:
    import scrublet as scr
except ImportError:  # Optional: only required for doublet detection.
    scr = None
from itertools import combinations
from matplotlib import pyplot as plt
from pathlib import Path

def pool_adatas(samples, sample_dir, csvFilenamesList, region_info= True, sample= True, batch= True, replicate= False, section= False,  reseg=False, exp_cond= False, run_info= False, rep_min= False, rep_min_switch= False, scrub= False, pcs= False):
    """
    Function to pool multiple runs and add brain region info.

    Args:
        samples (list): List of strings containing individual run hdf5 files.
        sample_dir (str): String specifying directory where samples reside.
        csvFilenamesList(list of str): A list of file path generated by glob.
        region_info(bool, optional): Whether to add brain region info. Defaults to True.
        sample (bool, optional): Whether to include sample in Anndata.obs. Defaults to True.
        batch (bool, optional):  Whether to include batch in Anndata.obs. Defaults to True.
        replicate (bool, optional): Whether to include replicate in Anndata.obs. Defaults to False.
        section (bool, optional): Whether to include section in Anndata.obs. Defaults to False.
        reseg (bool or str, optional): Specifies whether samples were resegmented or not. If resegmented, specify.  Defaults to False.
        exp_cond (bool or str, optional): Experimental condition aka grouping of interest of samples. Defaults to False.
        run_info (bool, dict, or pandas.DataFrame): Mapping of Region info to experimental condition.
        rep_min(bool or int, optional): Index to restart replicate count.
        rep_min_switch(bool or str, optional): Section identifier to restart replicate count.
        scrub (bool, optional): Whether to run scrublet to exclude doublets at this stage. Defaults to False.
        pcs (int, dict or bool, optional): Principal components (int or dict) for scrub. Defaults to False.

    Returns:
        List of pooled Anndata objects.

    """
    adatas = []
    if sample:
        i=1
    if batch:
        batch=1
        first= True
    if replicate:
        k= 1

    for s in samples:
        if reseg== False:
            idx1, idx2, area, roi,ext= s.replace('.','_').split("_")
            identifiers= [idx1, idx2, area, roi]
        else:
            idx1, idx2, area, roi,cp, ext= s.replace('.','_').split("_")
            identifiers= [idx1, idx2, area, roi]
        curr_adata = sc.read_h5ad(f"{sample_dir}/{s}")

        if region_info:
            csv_match = [s2 for s2 in csvFilenamesList if all([x in s2 for x in identifiers]) ]
            df= pd.read_csv(csv_match[0], engine= 'python')
            col1= df.columns[0]
            df[col1]= df[col1].astype(str)
            df.set_index(col1, inplace=True)
            df= df.reindex(curr_adata.obs_names)
            curr_adata.obs['Region']= df['Brain Region ID'].values
            brn= df['Brain Region Name']
            curr_adata.obs['Region Name'] = pd.Categorical(brn)

        if scrub:
            if isinstance(pcs, dict):
                this_pc= pcs[s]
            elif isinstance(pcs, int):
                this_pc= pcs
            else:
                this_pc= False
            curr_adata= exclude_doublets(curr_adata, savestr='', grouping= False,verbose= False, save=False, n_pcs= this_pc)
            del curr_adata.obs["doublet_scores"]

        if isinstance(exp_cond, str):
            if isinstance(run_info, dict):
                this_ec= run_info[s]
            elif isinstance(run_info, pd.DataFrame):
                dataset_info= curr_adata.obs['Datasets'][0][:-9]
                region_info= curr_adata.obs['Datasets'][0][-8:].replace('_',' ').capitalize()
                condition = (run_info['Run Name'].str.contains(dataset_info)) & (run_info['ROI'].str.contains(region_info))
                metadata_idx= run_info.loc[condition]
                this_ec= str(metadata_idx[f"{exp_cond}"].item())
            curr_adata.obs[f"{exp_cond}"]= this_ec
            curr_adata.obs[f"{exp_cond}"]= pd.Categorical([this_ec for i in range(curr_adata.shape[0])])

        if section:
            curr_adata.obs['section']= area
            curr_adata.obs['section']= pd.Categorical([area for y in range(curr_adata.shape[0])])

        if batch:
            if i%2==1 and not first:
                batch +=1
            curr_adata.obs['batch']= batch
            first= False

        if sample:
            curr_adata.obs['sample'] = i
            i+=1

        if replicate:
            if isinstance(rep_min, int) and isinstance(rep_min_switch, str) and rep_min_switch== area:
                curr_adata.obs['replicate']= k- rep_min
            else:
                curr_adata.obs['replicate']=k
            k+=1
        adatas.append(curr_adata)
    return adatas


def merge_adatas(adatas, region_info= True, sample= True, batch= True, replicate= False, section= False, exp_cond= False, layers= False):
    """_summary_

    Args:
        adatas (list of Anndata objects): Pooled Anndata objects.
        region_info (bool, optional): Whether region info was included in Anndata obs. Defaults to True.
        sample (bool, optional): Whether sample info was included in Anndata obs. Defaults to True.
        batch (bool, optional):  Whether batch info was included in Anndata obs. Defaults to True.
        replicate (bool, optional): Whether replicate info was included in Anndata obs. Defaults to False.
        section (bool, optional): Whether section info was included in Anndata obs. Defaults to False.
        exp_cond (bool or str, optional):  Whether experimental condition was speficied and included in Anndata obs. Defaults to False.
        layer(bool,str or list,optional): Whether to merge adata.layers. Defaults to False.


    Returns:
        Anndata object.
    """

    first=True
    for a in adatas:
        if first:
            cell_by_gene= a.to_df()
            cell_metadata= a.obs
            if layers:
                if isinstance(layers, list):
                    layer_dict= {l:None for l in layers}
                    for layer in layers:
                        layer_dict[layer]= a.layers[layer]
                else:
                    layer_df= a.layers[layers]
            first= False
        else:
            cell_by_gene= pd.concat([cell_by_gene, a.to_df()])
            cell_metadata= pd.concat([cell_metadata, a.obs])
            if layers:
                if isinstance(layers, list):
                    for layer in layers:
                        layer_dict[layer]= np.concatenate([layer_dict[layer]], a.layers[layer], axis=0)
                else:
                    layer_df= np.concatenate([layer_df, a.layers[layers]], axis=0)


    cell_metadata['Datasets']= cell_metadata['Datasets'].astype('category')
    if region_info:
        cell_metadata['Region Name']= cell_metadata['Region Name'].astype('category')
    if isinstance(exp_cond, str):
        cell_metadata[f"{exp_cond}"]= cell_metadata[f"{exp_cond}"].astype('category')
    if sample:
        cell_metadata['sample']= cell_metadata['sample'].astype('category')
    if batch:
        cell_metadata['batch']= cell_metadata['batch'].astype('category')
    if replicate:
        cell_metadata['replicate']= cell_metadata['replicate'].astype('category')
    if section:
        cell_metadata['section']= cell_metadata['section'].astype('category')
    pd.CategoricalIndex(cell_by_gene)
    pd.CategoricalIndex(cell_metadata)
    if layers:
        if isinstance(layers, list):
            adata = sc.AnnData(X=cell_by_gene, obs=cell_metadata)
            adata.layers = layer_dict
        else:
            adata = sc.AnnData(X=cell_by_gene, obs=cell_metadata, layers={layers: layer_df})
    else:
        adata= sc.AnnData(X= cell_by_gene, obs= cell_metadata)
    if region_info:
        adata= adata[adata.obs['Region Name'].notna()]
    keep_genes = [x for x in adata.var.index.tolist() if 'Blank'.lower() not in x.lower()]
    adata = adata[:, keep_genes]


    return adata



def run_bulk_qc(adata, col_suffixes= ['cell_count', 'avg_volume', 'avg_transcripts_per_cell', 'avg_unique_genes_per_cell'], row_names= False, exp_cond= False, multiple= False, mult_key= False, extra_groups= False, save_excel= False, nantozero= False, inplace= True, vol_key= 'volume'):
    """
    Run bulk quality control to assess and/or compare segmentation and cell/transcript quality.

    Args:
        adata (Anndata object): Pooled and merged Anndata object.
        col_suffixes (list of strings, optional): Column names or suffixes for quality control dataframe. Defaults to ['cell_count', 'avg_volume', 'avg_transcripts_per_cell', 'avg_unique_genes_per_cell'].
        row_names (bool or list of strings, optional): Row names for quality control dataframe. Defaults to False.
        exp_cond (bool or str, optional):  Whether experimental condition was speficied and included in Anndata obs. Defaults to False.
        multiple (bool, optional): Whether multiple versions of Anndata (i.e. resegmentation) is being collected in dataframe. Defaults to False.
        mult_key (bool or str, optional): If multiple versions, key for column prefixes. Defaults to False.
        extra_groups (bool or list of str, optional): If desired, adds extra level of grouping to quality control dataframe. Defaults to False.
        save_excel (bool or str, optional): False to return dataframe, string path to desired filename to save dataframe. Defaults to False.
        nantozero(bool, optional): Convert nan values in adata.X to 0. Default to False.
        inplace (bool, optional): Whether to modify anndata i.e. add qc metrics or return new. Defaults to True.
        vol_key (string, optional): Anndata obs indicating volume. Defaults to "volume".

    Returns:
        Anndata object.
        pd.Dataframe or None: Based on "save" argument, returns dataframe or saves to Excel file.
    """

    if multiple and isintance(mult_key, str):
        col_names= []
        for col_suffix in col_suffixes:
            col_names += [mult_key + '_' + col_suffix]
    else:
        col_names= col_suffixes

    if row_names== False and exp_cond==False and extra_groups== False:
        row_names= 'All'
    elif row_names ==False and extra_groups== False and isinstance(exp_cond,str):
        exp_cond_bin= np.unique(adata.obs[f"{exp_cond}"]).tolist()
        row_names= ['All'] + exp_cond_bin
    elif row_names ==False and isinstance(extra_groups,list):
        if isinstance(exp_cond,str):
            exp_cond_bin= np.unique(adata.obs[f"{exp_cond}"]).tolist()
            row_names= ['All'] + exp_cond_bin
        else:
            row_names= ['All']
        for extra_group in extra_groups:
            eg_bin= np.unique(adata.obs[f"{extra_group}"]).tolist()
            for eg in eg_bin:
                row_names += [extra_group + '_' + str(eg)]

    qc_df = pd.DataFrame(columns=col_names, index=row_names)

    if inplace:
        if nantozero:
            adata.X= np.nan_to_num(adata.X, nan=0)
        sc.pp.calculate_qc_metrics(adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)
        sc.pp.calculate_qc_metrics(adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)
        curr_adata=adata
    else:
        if nantozero:
            curr_adata= adata.copy()
        curr_adata.X= np.nan_to_num(curr_adata.X, nan=0)
        sc.pp.calculate_qc_metrics(curr_adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)
        sc.pp.calculate_qc_metrics(curr_adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)


    this_row= "All"
    if multiple and isinstance(mult_key, str):
        col_prefix= mult_key + '_'
    else:
        col_prefix= ''
    qc_df.loc[this_row, f"{col_prefix}cell_count"]= curr_adata.n_obs
    qc_df.loc[this_row, f"{col_prefix}avg_volume"]= np.mean(curr_adata.obs[vol_key])
    qc_df.loc[this_row, f"{col_prefix}avg_transcripts_per_cell"]= np.mean(curr_adata.obs['total_counts'])
    qc_df.loc[this_row, f"{col_prefix}avg_unique_genes_per_cell"]= np.mean(curr_adata.obs['n_genes_by_counts'])
    if isinstance(exp_cond, str):
        exp_cond_bin= np.unique(curr_adata.obs[f"{exp_cond}"]).tolist()
        for ec_bin in exp_cond_bin:
            curr_adata_ec= curr_adata[curr_adata.obs[f"{exp_cond}"]== ec_bin].copy()
            this_row= f"{ec_bin}"
            qc_df.loc[this_row, f"{col_prefix}cell_count"]= curr_adata_ec.n_obs
            qc_df.loc[this_row, f"{col_prefix}avg_volume"]= np.mean(curr_adata_ec.obs[vol_key])
            qc_df.loc[this_row, f"{col_prefix}avg_transcripts_per_cell"]= np.mean(curr_adata_ec.obs['total_counts'])
            qc_df.loc[this_row, f"{col_prefix}avg_unique_genes_per_cell"]= np.mean(curr_adata_ec.obs['n_genes_by_counts'])
    if isinstance(extra_groups, list):
        for extra_group in extra_groups:
            eg_bin= np.unique(curr_adata.obs[f"{extra_group}"]).tolist()
            for eg in eg_bin:
                curr_adata_eg= curr_adata[curr_adata.obs[f"{extra_group}"]== eg].copy()
                this_row= f"{extra_group}_{eg}"
                qc_df.loc[this_row, f"{col_prefix}cell_count"]= curr_adata_eg.n_obs
                qc_df.loc[this_row, f"{col_prefix}avg_volume"]= np.mean(curr_adata_eg.obs[vol_key])
                qc_df.loc[this_row, f"{col_prefix}avg_transcripts_per_cell"]= np.mean(curr_adata_eg.obs['total_counts'])
                qc_df.loc[this_row, f"{col_prefix}avg_unique_genes_per_cell"]= np.mean(curr_adata_eg.obs['n_genes_by_counts'])
    if isinstance(save_excel, str):
        qc_df.to_excel(save_excel)
        return curr_adata
    else:
        return curr_adata, qc_df

def exclude_doublets(adata, savestr, grouping= 'sample',verbose= False, save=True, n_pcs= False):
    """
    Run Scrublet on pooled adata to exclude doublets and save.

    Args:
        adata (Anndata object): Pooled and merged Anndata object.
        savestr (str): String path to desired filename to save Anndata.
        grouping (str or bool, optional): Anndata.obs grouping by which Anndata will be subset for doubleting. Defaults to 'sample'.
        verbose (bool, optional): Verbosity of scrublet process. Defaults to False.
        save (bool, optional): Whether to save Anndata object post-scrub. Defaults to True.
        n_pcs= (bool or int, optional): Number of principal components to pass to scrublet if it fails due to n_samples, n_features error.

    Returns:
        Anndata object.
    """


    if scr is None:
        raise ImportError(
            "Scrublet is required for doublet detection. Install the optional "
            "dependencies with `pip install -e '.[scrublet]'` or "
            "`pip install -r environment_exports/requirements-scrublet.txt`."
        )

    if isinstance(grouping, str):
        all_doublet_scores = []
        for i in adata.obs[f"{grouping}"].unique():
            if verbose:
                print("Doubleting", i)
            curr_adata = adata[adata.obs[f"{grouping}"]==i]
            scrub = scr.Scrublet(curr_adata.X)
            if n_pcs:
                doublet_scores, predicted_doublets = scrub.scrub_doublets(log_transform=True, n_prin_comps=n_pcs)
            else:
                doublet_scores, predicted_doublets = scrub.scrub_doublets(log_transform=True)
            all_doublet_scores.append(doublet_scores)
    else:
        curr_adata= adata.copy()
        scrub = scr.Scrublet(curr_adata.X)
        if n_pcs:
            all_doublet_scores, predicted_doublets = scrub.scrub_doublets(log_transform=True, n_prin_comps=n_pcs)
        else:
            all_doublet_scores, predicted_doublets = scrub.scrub_doublets(log_transform=True)


    adata.obs["doublet_scores"] = np.hstack(all_doublet_scores)

    adata= adata[adata.obs["doublet_scores"]<0.2]
    if save:
        adata.write(savestr)
    return adata


def qc_plots(adata, fig_dir= sc.settings.figdir, plot_types= ['histogram', 'violin', 'scatter'], obs= ['volume', 'total_counts', 'n_genes_by_counts'],vlines= {'volume':100, 'total_counts':500, 'n_genes_by_counts': 30}, xlims= {'volume':5000, 'total_counts': 3000, 'n_genes_by_counts': 350}, bins= {'volume':100, 'total_counts': 100, 'n_genes_by_counts': 10} , verbose= True, groupby= False, ticks= True, calc_qc= False, median= True, save= False):
    """
    Quality control plots.

    Args:
        adata (Anndata object): Adata to be plotted.
        fig_dir (str or PosixPath, optional): Directory where figures are saved. Defaults to sc.settings.figdir.
        plot_types (list, optional): Types of plots to visualize. Defaults to ['histogram', 'violin', 'scatter'].
        obs (list, optional): Anndata obs to be plotted. Defaults to ['volume', 'total_counts', 'n_genes_by_counts'].
        vlines (dict, optional): Dictionary specifying X coordinates of vertical lines per obs. Defaults to {'volume':100, 'total_counts':500, 'n_genes_by_counts': 30}.
        xlims (dict, optional):  Dictionary specifying X coordinate limits per obs. Defaults to {'volume':5000, 'total_counts': 3000, 'n_genes_by_counts': 350}.
        bins (dict, optional):  Dictionary specifying no of bins per obs. Defaults to {'volume':100, 'total_counts': 100, 'n_genes_by_counts': 10}.
        verbose (bool, optional): Whether to print extra info e.g. mean volume per sample. Defaults to True.
        groupby (bool or list of str, optional): Grouping specified by Anndata.obs to split up plots e.g. 'age', 'sample'. Defaults to False.
        ticks (bool, optional): Whether to add ticks to plots. Defaults to True.
        calc_qc (bool, optional): Whether to calculate qc metrics prior to plotting. Defaults to False.
        median (bool, optional): Whether to replace vline values with median values from adata. Defaults to False.
        save (bool, optional): Whether to display or save plots. Defaults to False and displays.
    """
    fig_dir= Path(fig_dir)

    if calc_qc:
        sc.pp.calculate_qc_metrics(adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)
        sc.pp.calculate_qc_metrics(adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)


    if median:
        del vlines
        median_vol= np.median(adata.obs.volume)
        median_total_counts= np.median(adata.obs.total_counts)
        median_n_genes_by_counts= np.median(adata.obs.n_genes_by_counts)
        vlines= {
            'volume': median_vol,
            'total_counts': median_total_counts,
            'n_genes_by_counts': median_n_genes_by_counts
        }
        if verbose:
            print(f"median volume:{median_vol}, median transcript counts: {median_total_counts}, median unique genes: {median_n_genes_by_counts}")


    for plot_type in plot_types:
        if plot_type == "histogram":
            for ob in obs:
                if isinstance(groupby, list) :
                    for group in groupby:
                        unique_groups= np.unique(adata.obs[f"{group}"])
                        fig_y = 6 * (len(unique_groups)/2)
                        fig, axes= plt.subplots(len(unique_groups), sharey= True, figsize= (6, fig_y))
                        plt.subplots_adjust(hspace=0.4)
                        for i,ax in enumerate(axes):
                            if verbose:
                                curr_group= group + '_' + str(unique_groups[i])
                                print(ob, curr_group ,np.mean(adata[adata.obs[f"{group}"]==unique_groups[i]].obs[f"{ob}"]))
                            ax.set_xlim([0,xlims[ob]])
                            ax.hist(adata[adata.obs[f"{group}"]==unique_groups[i]].obs[f"{ob}"],bins= range(0, xlims[ob], bins[ob]))
                            ax.set_title(f"{group} {unique_groups[i]} {ob}")
                            if isinstance(vlines, dict):
                                ax.axvline(vlines[ob])
                            if ticks:
                                xticks= range(0, xlims[ob], bins[ob])
                                ax.set_xticks(xticks)
                                xticks_label = ['{}'.format(num) if num % bins[ob] == 0 else ' ' for num in xticks]
                                ax.set_xticklabels(xticks_label, rotation =75,size= 7)
                                ax.grid(True)
                        plt.suptitle(f"{ob} across {group}")
                        if save:
                            plt.savefig(f"{fig_dir}/{plot_type}_{ob}_{group}")
                        else:
                            plt.show()
                else:
                    with plt.rc_context({"figure.figsize": (10, 10)}):
                        plt.hist(adata.obs[f"{ob}"], bins= range(0,xlims[ob], bins[ob]))
                        plt.xlim([0, xlims[ob]])
                        if ticks:
                            plt.gca().set_xticks(range(0, int(plt.gca().get_xlim()[1]) + 1, bins[ob]))
                            plt.tick_params(axis='x', which='major', labelsize=10)
                            plt.xticks(rotation=75)
                        if isinstance(vlines, dict):
                            ax.axvline(vlines[ob])
                        plt.title(f"{ob}")
                        if save:
                            plt.savefig(f"{fig_dir}/{plot_type}_{ob}")
                        else:
                            plt.show()
        elif plot_type == "violin":
            if isinstance(groupby, list):
                for group in groupby:
                    fig_y= 5 * len(obs)
                    fig, axes= plt.subplots(3, figsize=(5,fig_y))
                    plt.subplots_adjust(hspace=0.4)
                    for i,ax in enumerate(axes):
                        sc.pl.violin(adata, obs[i],groupby= group, stripplot= False, inner= 'box', jitter=False, legend= False, show=False, ax=ax)
                        ax.set_title(f"{obs[i]} by {group}")
                        if ticks:
                            yticks= range(0, int(ax.get_ylim()[1]) + 1, bins[obs[i]]*5)
                            ax.set_yticks(yticks)
                            yticks_label = ['{}'.format(num) if num % (bins[obs[i]]*10) == 0 else ' ' for num in yticks]
                            ax.set_yticklabels(yticks_label)
                    plt.suptitle(f"QC Plots by {group}")
                    if save:
                        plt.savefig(f"{fig_dir}/{plot_type}_{group}")
                    else:
                        plt.show()
            else:
                fig_y= 5 * len(obs)
                fig, axes= plt.subplots(3, figsize=(5,fig_y))
                plt.subplots_adjust(hspace=0.4)
                for i,ax in enumerate(axes):
                    sc.pl.violin(adata, obs[i], stripplot= False, inner= 'box', jitter=False, show=False, ax=ax)
                    ax.set_title(f"{obs[i]}")
                    if ticks:
                        yticks= range(0, int(ax.get_ylim()[1]) + 1, bins[obs[i]]*5)
                        ax.set_yticks(yticks)
                        yticks_label = ['{}'.format(num) if num % (bins[obs[i]]*10) == 0 else ' ' for num in yticks]
                        ax.set_yticklabels(yticks_label)
                plt.suptitle(f"QC Plots")
                if save:
                    plt.savefig(f"{fig_dir}/{plot_type}")
                else:
                    plt.show()
        elif plot_type == "scatter":
            if len(obs)>1:
                combo_list= list(combinations(obs, 2))
                fig_x= 5 * len(combo_list)
                if isinstance(groupby, list):
                    for group in groupby:
                        unique_groups= np.unique(adata.obs[f"{group}"])
                        fig_y= 5* len(unique_groups)
                        fig, axes= plt.subplots(nrows= len(unique_groups), ncols= len(combo_list), figsize=(fig_x,fig_y))
                        plt.subplots_adjust(hspace=0.4, wspace=0.2)
                        for row in range(len(unique_groups)):
                            curr_adata= adata[adata.obs[f"{group}"]== unique_groups[row]].copy()
                            # fig.text(0.5, 1 - (row + 0.5) / 4, f"{group} {unique_groups[row]}", ha='center', fontsize=14, fontweight='bold')
                            for col in range(len(combo_list)):
                                combo= combo_list[col]
                                ax= axes[row, col]
                                sc.pl.scatter(curr_adata, combo[0], combo[1], size=2,show=False, ax=ax)
                                ax.set_xlim([0,xlims[combo[0]]])
                                ax.set_ylim([0,xlims[combo[1]]])
                                ax.set_title(f"{group} {unique_groups[row]} {combo[0]} vs {combo[1]}")
                                if isinstance(vlines, dict):
                                    ax.axhline(vlines[combo[1]])
                                    ax.axvline(vlines[combo[0]])
                        plt.suptitle(f"Scatterplots of QC Combos Across {group}")
                        if save:
                            plt.savefig(f"{fig_dir}/{plot_type}_{group}")
                        else:
                            plt.show()
                else:
                    fig, axes= plt.subplots(nrows=1, ncols= len(combo_list), figsize=(fig_x,5))
                    plt.subplots_adjust(hspace=0.4)
                    for i,ax in enumerate(axes):
                        combo= combo_list[i]
                        sc.pl.scatter(adata, combo[0], combo[1], size=2,show=False, ax=ax)
                        ax.set_xlim([0,xlims[combo[0]]])
                        ax.set_ylim([0,xlims[combo[1]]])
                        if isinstance(vlines, dict):
                            ax.axhline(vlines[combo[1]])
                            ax.axvline(vlines[combo[0]])
                    plt.title("Scatterplots of QC Combos")
                    if save:
                        plt.savefig(f"{fig_dir}/{plot_type}")
                    else:
                        plt.show()



def save_adatas(adata, filenames, dir_path, this_ext, groupby=False):
    """
    Save and export Anndata as hdf5 with optional grouping by sample or batch.

    Args:
        adata (Anndata object): Adata to be saved
        filenames (list of str): Filenames to be saved, can be original filenames to be updated with an extension, should end with hdf5.
        dir_path (str): Path to directory where adatas will be saved.
        this_ext (str): String extension, useful to modify original sample filenames, can also be passed as empty.
        groupby (bool or str, optional): Whether to include a grouping to split up adata while saving. Defaults to False. Other options are "sample" or "batch".
    """
    if isinstance(groupby, str):
        j=0
        for i in adata.obs[f"{groupby}"].unique():
            curr_adata = adata[adata.obs[f"{groupby}"]==i].copy()
            if groupby== "sample":
                this_index= filenames[j].index('.hdf5')
                filepath= dir_path + filenames[j][:this_index] + this_ext + filenames[j][this_index:]
                j+=1
            elif groupby == "batch":
                this_index= filenames[j].index('Region')
                filepath= dir_path + filenames[j][:this_index] + this_ext.replace('/','_') + '.hdf5'
                j+=2
            curr_adata.write(filepath)
    else:
        this_index= filenames[0].index('.hdf5')
        filepath= f"{dir_path}/{filenames[0][:this_index]}{this_ext}{filenames[0][this_index:]}"
        adata.write(filepath)


def run_default_cluster_pp(adata, vol_filter= True, quantiles= (0.2, 0.9), min_counts= 30, min_genes=5, min_cells= 3, norm_target_sum= 500, log1p= True, scale_max= 10, verbose= True, inplace= True, raw_layer= True, save= False, recalc_qc= False, vol_key= 'volume'):
    """
    Run default preprocessing pipeline for clustering. NOT intended for differential gene expression modeling!

    Args:
        adata (Anndata object): Adata to be preprocessed for clustering.
        vol_filter (bool, optional): Whether to filter by volume. Defaults to True.
        quantiles (tuple, optional): Quantiles to use for volume filtering. Defaults to (0.2, 0.9).
        min_counts (bool or int, optional): Minimum transcript counts per cell for filtering. Defaults to 30.
        min_genes (bool or int, optional): Minimum unique genes per cell for filtering. Defaults to 5 i.e. cells with less than 5 unique genes will be filtered out.
        min_cells (bool or int, optional): Minimum number of cells required to express gene to retain. Defaults to 3.
        norm_target_sum (bool or int, optional): Target sum of total transcripts for normalization. Defaults to 500.
        log1p (bool, optional): Whether to logarithmize data. Defaults to True.
        scale_max (bool or int, optional): Value to clip counts when scaling to zero mean and unit variance. Defaults to 10.
        verbose (bool, optional): Whether to print summary stats and details throughout filtering process. Defaults to True.
        inplace (bool, optional): Whether to modify adata in place or return new adata. Defaults to True.
        raw_layer (bool, optional): Whether to save raw counts in adata.layers['raw_counts']. Defaults to True.
        save (bool or str, optional): Whether to save adata. Defaults to False. Provide filepath str to save.
        recalc_qc (bool, optional): Whether to recalculate quality metrics. Good idea if genes have been subset. Defauls to False.

    Returns:
        Preprocessed Anndata object ready for clustering.
    """
    if inplace:
        curr_adata= adata
    else:
        curr_adata= adata.copy()

    if vol_filter:
        pre_vol_filter= curr_adata.n_obs
        pre_median_vol= np.median(curr_adata.obs[vol_key])
        min_vol= np.quantile(curr_adata.obs[vol_key], quantiles[0])
        max_vol= np.quantile(curr_adata.obs[vol_key], quantiles[1])
        curr_adata= curr_adata[np.logical_and(curr_adata.obs[vol_key] >= min_vol, curr_adata.obs[vol_key] < max_vol)]
        post_median_vol= np.median(curr_adata.obs[vol_key])
        post_vol_filter= curr_adata.n_obs
        if verbose:
            print(f"With {quantiles[0]} as lower and {quantiles[1]} as upper quantiles, set min vol to {min_vol} and max vol to {max_vol}.")
            print(f"Started with {pre_vol_filter} cells, excluded {pre_vol_filter- post_vol_filter} cells.")
            print(f"Initial median volume pre filter was {pre_median_vol}, and post filter median volume is {post_median_vol}.")

    if min_counts:
        pre_cell_filter= curr_adata.n_obs
        if verbose:
            print(f"Cell count before filtering cells by transcript counts: {pre_cell_filter}.")
        sc.pp.filter_cells(curr_adata, min_counts= min_counts)
        post_cell_filter= curr_adata.n_obs
        if verbose:
            print(f"Filtered {pre_cell_filter- post_cell_filter} cells with less than {min_counts} counts, amounting to {post_cell_filter} cells.")

    if min_genes:
        sc.pp.filter_cells(curr_adata, min_genes=min_genes)
        post_cell_filter2= curr_adata.n_obs
        if verbose:
            print(f"Filtered {post_cell_filter- post_cell_filter2} cells with less than {min_genes} genes, amounting to {post_cell_filter2} cells.")

    if min_cells:
        pre_gene_filter= curr_adata.n_vars
        sc.pp.filter_genes(curr_adata, min_cells=min_cells)
        post_gene_filter= curr_adata.n_vars
        if verbose:
            print(f"Starting with {pre_gene_filter} genes, filtered {pre_gene_filter- post_gene_filter} genes expressed in less than {min_cells} cells, amounting to {post_gene_filter} genes.")

    if recalc_qc:
        sc.pp.calculate_qc_metrics(curr_adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)
        sc.pp.calculate_qc_metrics(curr_adata, qc_vars=(), percent_top=None, log1p=False, inplace=True)

    if verbose:
        median_total_counts= np.median(curr_adata.obs.total_counts)
        median_unique_genes= np.median(curr_adata.obs.n_genes_by_counts)
        print(f"After all filtering, median total counts per cell are {median_total_counts} and median unique genes per cell are {median_unique_genes}.")


    if raw_layer:
        curr_adata.layers["raw_counts"] = curr_adata.X.copy()
        if verbose:
            print(f"Copied raw count matrix to 'raw count' layer of Anndata object.")

    if norm_target_sum:
        sc.pp.normalize_total(curr_adata, target_sum=norm_target_sum)
        if verbose:
            print(f"Normalized total counts per cell to {norm_target_sum}.")

    if log1p:
        sc.pp.log1p(curr_adata)
        curr_adata.raw= curr_adata
        if verbose:
            print("Completed natural logarithm transformation of count matrix.")

    if scale_max:
        sc.pp.scale(curr_adata, max_value=scale_max)
        if verbose:
            print(f"Scaled data to unit variance and 0 mean, values clipped to {scale_max}.")

    if isinstance(save, str):
        curr_adata.write(save)

    return curr_adata


def subset_genes(adata, select_genes, other_genes= [], inplace=True):
    """
    Subset adata to a select subset of genes.

    Args:
        adata (Anndata object): Adata to be subset.
        select_genes (list of str): List of genes to be retained.
        other_genes (list or dict, optional): Other list of genes to be included, e.g. marker genes. Defaults to [].
        inplace (bool, optional): Whether to modify adata in place or return new adata. Defaults to True.

    Returns:
        curr_adata (Anndata object): Subsetted adata.
    """

    if inplace:
        curr_adata= adata
    else:
        curr_adata= adata.copy()
    if isinstance(other_genes, dict):
        other_genes_list=  []
        for key in other_genes:
            other_genes_list += other_genes[key]
        other_genes= other_genes_list

    select_genes += other_genes
    select_genes= [x[:1].upper() + x[1:].lower() for x in select_genes]
    select_genes=np.unique(select_genes).tolist()
    int_genes= [value for value in curr_adata.var_names if value in select_genes]

    curr_adata = curr_adata[:, int_genes]

    return curr_adata


def subset_brain_regions(adata, specific_regions, this_obs= 'Region Name', exclude_regions= False, inplace=True):
    """
    Subset adata to cells in specific brain regions and/or exclude cells in specified regions.

    Args:
        adata (Anndata object): Adata to be subset.
        specific_regions (list of str or bool): List of brain regions to be retained.
        this_obs (str, optional): Anndata.obs name to access brain region info. Defaults to 'Region Name'.
        exclude_regions (bool or list of str, optional): Whether to exclude brain regions. Defaults to False. Can be a list of regions to be excluded.
        inplace (bool, optional): Whether to modify adata in place or return new adata. Defaults to True.

    Returns:
        curr_adata (Anndata object): Subsetted adata.
    """
    if inplace:
        curr_adata= adata
    else:
        curr_adata= adata.copy()

    if specific_regions:
        curr_adata= curr_adata[curr_adata.obs[this_obs].isin(specific_regions)]

    if exclude_regions:
        curr_adata= curr_adata[~curr_adata.obs[this_obs].isin(exclude_regions)]

    return curr_adata

def extract_gene_info(genes_list, gene_col= 'Gene', prefix=None ):
    if isinstance(genes_list, str):
        genes_list= pd.read_excel(genes_list)

    if gene_col in genes_list.columns:
        genes_list.set_index(gene_col, inplace=True)

    if isinstance(prefix, str):
        these_cols= [column for column in  genes_list.columns if prefix in column]
        genes_list= genes_list.loc[:, these_cols]

    gene_info= {this_idx.capitalize():[] for this_idx in genes_list.index}

    for index, row in genes_list.iterrows():
        index= index.capitalize()
        for col in genes_list.columns:
            if pd.notna(row[col]):
                this_idx= row[col].find("(")
                if this_idx == -1:
                    gene_info[index]+= [row[col]]
                else:
                    gene_info[index]+= [row[col][:this_idx-1]]

    return gene_info









# def subset_ontology(adata, main_target_structures, ontology, )
