#!/usr/bin/env python3
"""
Pool and preprocess the public SenNet CosMx mouse-brain datasets.

Expected inputs
---------------
1. A directory containing one downloaded raw CosMx folder per young-old pair.
   Each folder must be named with one of the SenNet dataset IDs recorded in
   the run-metadata workbook and must contain, possibly in a nested ``raw``
   directory:

   - ``*exprMat_file.csv``
   - ``*metadata_file.csv``

   The paired young and old SenNet records contain duplicate copies of these
   files, so only one dataset folder is required per pair.

2. ``CosMx Data.xlsx``, with the columns:

   - Dataset ID
   - Pair
   - Age
   - Plane
   - Fov Start
   - Fov End

Processing
----------
- Pool the four CosMx pairs.
- Assign age and anatomical plane from the metadata workbook and FOV ranges.
- Remove doublets within pair x age x plane groups.
- Apply the original bulk-QC and default clustering-preprocessing workflow.
- Retain transformed counts in ``adata.layers['transformed_counts']`` and raw
  transcript counts in ``adata.layers['raw_counts']``.
- Convert mouse gene symbols to Ensembl gene identifiers using MyGene.
- Restrict the MapMyCells query object to the requested anatomical plane.
- Place raw counts in ``adata.X`` and Ensembl IDs in ``adata.var_names``.

Outputs
-------
- ``cosmx_data_rawx_ensembl.h5ad``: MapMyCells-ready AnnData object.
- ``cosmx_data_postscrub_prefilter_qc.xlsx``: QC summary before filtering.
- ``cosmx_data_postscrub_postfilter_qc.xlsx``: QC summary after filtering.
- ``cosmx_gene_symbol_to_ensembl.csv``: frozen gene-ID mapping used in output.
- ``cosmx_preprocessing_run_configuration.json``: input paths, parameters,
  package versions, and processing summary.
- Intermediate doublet-removal and preprocessing files generated by
  ``kimlabspatial``.

Example
-------
python preprocess_cosmx.py \
    --input-dir data/raw/cosmx \
    --run-metadata "metadata/CosMx Data.xlsx" \
    --output-dir data/processed/cosmx \
    --plane Anterior
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
from pathlib import Path
import sys
from typing import Any
import warnings

import anndata as ad
import mygene
import numpy as np
import pandas as pd
import scanpy as sc

import kimlabspatial.preprocessing as pp


REQUIRED_METADATA_COLUMNS: tuple[str, ...] = (
    "Dataset ID",
    "Pair",
    "Age",
    "Plane",
    "Fov Start",
    "Fov End",
)

AGE_LABELS: dict[int, str] = {
    4: "Yng",
    24: "Old",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Pool, QC, and prepare the public SenNet CosMx data for "
            "MapMyCells."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help=(
            "Directory containing one downloaded dataset folder per pair. "
            "Folder names must match a Dataset ID in the metadata workbook."
        ),
    )
    parser.add_argument(
        "--run-metadata",
        type=Path,
        required=True,
        help="Excel workbook defining dataset IDs, pairs, ages, planes, and FOV ranges.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory in which processed data and QC summaries will be written.",
    )
    parser.add_argument(
        "--output-name",
        default="cosmx_data_rawx_ensembl.h5ad",
        help="Filename for the final MapMyCells-ready H5AD.",
    )
    parser.add_argument(
        "--plane",
        default="Anterior",
        help=(
            "Anatomical plane retained in the final MapMyCells query object. "
            "Use 'all' to retain all planes. Default: Anterior."
        ),
    )
    parser.add_argument(
        "--n-features",
        type=int,
        default=1001,
        help=(
            "Number of feature columns retained from each expression matrix "
            "after removing CosMx identifier columns. Default: 1001, matching "
            "the original analysis."
        ),
    )
    parser.add_argument(
        "--volume-key",
        default="Area.um2",
        help="Cell-area/volume column used by kimlabspatial QC. Default: Area.um2.",
    )
    parser.add_argument(
        "--lower-quantile",
        type=float,
        default=0.1,
        help="Lower filtering quantile passed to run_default_cluster_pp.",
    )
    parser.add_argument(
        "--upper-quantile",
        type=float,
        default=0.9,
        help="Upper filtering quantile passed to run_default_cluster_pp.",
    )
    parser.add_argument(
        "--gene-map",
        type=Path,
        default=None,
        help=(
            "Optional existing CSV with columns gene_symbol and ensembl_id. "
            "When supplied, no live MyGene queries are performed."
        ),
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow existing output files to be replaced.",
    )
    return parser.parse_args()


def require_file(path: Path, description: str) -> Path:
    path = path.expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f"{description} does not exist: {path}")
    return path


def require_directory(path: Path, description: str) -> Path:
    path = path.expanduser().resolve()
    if not path.is_dir():
        raise NotADirectoryError(f"{description} does not exist: {path}")
    return path


def package_version(package: str) -> str:
    try:
        return importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        return "not installed"


def load_run_metadata(path: Path) -> pd.DataFrame:
    metadata = pd.read_excel(path)
    missing = [column for column in REQUIRED_METADATA_COLUMNS if column not in metadata]
    if missing:
        raise ValueError(
            "Run-metadata workbook is missing required columns: " + ", ".join(missing)
        )

    metadata = metadata.loc[:, REQUIRED_METADATA_COLUMNS].copy()
    metadata["Dataset ID"] = metadata["Dataset ID"].astype(str).str.strip()

    numeric_columns = ("Pair", "Age", "Fov Start", "Fov End")
    for column in numeric_columns:
        metadata[column] = pd.to_numeric(metadata[column], errors="raise").astype(int)

    if metadata.duplicated(["Pair", "Age", "Plane"]).any():
        duplicated = metadata.loc[
            metadata.duplicated(["Pair", "Age", "Plane"], keep=False),
            ["Pair", "Age", "Plane"],
        ]
        raise ValueError(
            "Run metadata contains duplicate pair-age-plane rows:\n"
            + duplicated.to_string(index=False)
        )

    invalid_ranges = metadata["Fov Start"] > metadata["Fov End"]
    if invalid_ranges.any():
        raise ValueError("One or more FOV ranges have Fov Start greater than Fov End.")

    return metadata.sort_values(["Pair", "Fov Start"]).reset_index(drop=True)


def find_pair_files(
    input_dir: Path,
    pair_metadata: pd.DataFrame,
) -> tuple[Path, Path, str]:
    """Find one expression/metadata file pair using either dataset ID for a pair."""
    matches: list[tuple[Path, Path, str]] = []

    for dataset_id in pair_metadata["Dataset ID"].drop_duplicates():
        dataset_dir = input_dir / dataset_id
        if not dataset_dir.is_dir():
            continue

        expression_files = sorted(dataset_dir.rglob("*exprMat_file.csv"))
        metadata_files = sorted(dataset_dir.rglob("*metadata_file.csv"))

        if len(expression_files) != 1 or len(metadata_files) != 1:
            raise FileNotFoundError(
                f"Expected exactly one *exprMat_file.csv and one "
                f"*metadata_file.csv under {dataset_dir}; found "
                f"{len(expression_files)} and {len(metadata_files)}, respectively."
            )

        matches.append((expression_files[0], metadata_files[0], dataset_id))

    if not matches:
        expected = ", ".join(pair_metadata["Dataset ID"].drop_duplicates())
        pair = int(pair_metadata["Pair"].iloc[0])
        raise FileNotFoundError(
            f"No downloaded folder was found for pair {pair}. Expected one of: {expected}"
        )

    if len(matches) > 1:
        warnings.warn(
            "Both duplicated dataset folders were found for pair "
            f"{int(pair_metadata['Pair'].iloc[0])}. Using {matches[0][2]} and "
            "ignoring the redundant copy.",
            stacklevel=2,
        )

    return matches[0]


def assign_design_metadata(
    cell_metadata: pd.DataFrame,
    pair_metadata: pd.DataFrame,
) -> pd.DataFrame:
    if "fov" not in cell_metadata.columns:
        raise ValueError("CosMx metadata file does not contain the required 'fov' column.")
    if "cell" not in cell_metadata.columns:
        raise ValueError("CosMx metadata file does not contain the required 'cell' column.")

    result = cell_metadata.copy()
    result["pair"] = int(pair_metadata["Pair"].iloc[0])
    result["num_age"] = pd.NA
    result["plane"] = pd.NA
    assignment_count = pd.Series(0, index=result.index, dtype=int)

    for row in pair_metadata.itertuples(index=False):
        mask = result["fov"].between(row[4], row[5], inclusive="both")
        result.loc[mask, "num_age"] = row[2]
        result.loc[mask, "plane"] = row[3]
        assignment_count.loc[mask] += 1

    unassigned = assignment_count == 0
    multiply_assigned = assignment_count > 1
    if unassigned.any() or multiply_assigned.any():
        raise ValueError(
            "FOV ranges did not assign every cell exactly once for pair "
            f"{int(pair_metadata['Pair'].iloc[0])}: "
            f"{int(unassigned.sum())} unassigned and "
            f"{int(multiply_assigned.sum())} multiply assigned."
        )

    result["num_age"] = pd.to_numeric(result["num_age"], errors="raise").astype(int)
    unexpected_ages = sorted(set(result["num_age"]) - set(AGE_LABELS))
    if unexpected_ages:
        raise ValueError(f"No age labels are defined for ages: {unexpected_ages}")

    result["age"] = result["num_age"].map(AGE_LABELS)
    result["age_plane"] = result["age"].astype(str) + "_" + result["plane"].astype(str)

    result = result.set_index("cell")
    result.index = result.index.astype(str)
    result.index.name = None

    for column in ("pair", "num_age", "plane", "age", "age_plane"):
        result[column] = pd.Categorical(result[column])

    return result


def prepare_count_matrix(counts: pd.DataFrame, n_features: int) -> pd.DataFrame:
    if "cell" not in counts.columns:
        raise ValueError("CosMx expression matrix does not contain the required 'cell' column.")

    result = counts.copy().set_index("cell")
    result.index = result.index.astype(str)
    result.index.name = None

    result = result.drop(columns=["fov", "cell_ID"], errors="ignore")
    if result.shape[1] < n_features:
        raise ValueError(
            f"Expression matrix contains {result.shape[1]} feature columns after "
            f"identifier removal, fewer than --n-features={n_features}."
        )
    result = result.iloc[:, :n_features]

    non_numeric = [column for column in result if not pd.api.types.is_numeric_dtype(result[column])]
    if non_numeric:
        raise TypeError(
            "Non-numeric columns remain in the expression matrix: "
            + ", ".join(map(str, non_numeric[:10]))
        )

    return result


def pool_pairs(
    input_dir: Path,
    run_metadata: pd.DataFrame,
    n_features: int,
) -> tuple[ad.AnnData, list[dict[str, str]]]:
    count_tables: list[pd.DataFrame] = []
    metadata_tables: list[pd.DataFrame] = []
    source_files: list[dict[str, str]] = []

    for pair in sorted(run_metadata["Pair"].unique()):
        pair_metadata = run_metadata.loc[run_metadata["Pair"] == pair].copy()
        expression_path, metadata_path, dataset_id = find_pair_files(
            input_dir,
            pair_metadata,
        )

        counts = prepare_count_matrix(pd.read_csv(expression_path), n_features)
        cell_metadata = assign_design_metadata(pd.read_csv(metadata_path), pair_metadata)

        missing_in_metadata = counts.index.difference(cell_metadata.index)
        missing_in_counts = cell_metadata.index.difference(counts.index)
        if len(missing_in_metadata) or len(missing_in_counts):
            raise ValueError(
                f"Cell identifiers do not match for pair {pair}: "
                f"{len(missing_in_metadata)} count-only cells and "
                f"{len(missing_in_counts)} metadata-only cells."
            )

        cell_metadata = cell_metadata.loc[counts.index].copy()
        count_tables.append(counts)
        metadata_tables.append(cell_metadata)
        source_files.append(
            {
                "pair": str(pair),
                "dataset_id_used": dataset_id,
                "expression_file": str(expression_path),
                "metadata_file": str(metadata_path),
            }
        )

    pooled_counts = pd.concat(count_tables, axis=0)
    pooled_metadata = pd.concat(metadata_tables, axis=0)

    if pooled_counts.index.has_duplicates:
        duplicated = pooled_counts.index[pooled_counts.index.duplicated()].unique()
        raise ValueError(
            "Cell identifiers are not globally unique after pooling. Examples: "
            + ", ".join(map(str, duplicated[:10]))
        )

    if not pooled_counts.columns.equals(count_tables[0].columns):
        raise ValueError("Feature columns differ across the pooled CosMx pairs.")

    pooled = ad.AnnData(X=pooled_counts, obs=pooled_metadata)
    pooled.obs["pair_age_plane"] = pd.Categorical(
        pooled.obs["pair"].astype(str)
        + "_"
        + pooled.obs["age"].astype(str)
        + "_"
        + pooled.obs["plane"].astype(str)
    )
    return pooled, source_files


def query_mygene(gene_symbols: pd.Index) -> pd.DataFrame:
    mg = mygene.MyGeneInfo()
    records: list[dict[str, str]] = []

    for symbol in gene_symbols.astype(str):
        ensembl_id = ""
        status = "not_found"

        if "/" in symbol:
            status = "skipped_merged_symbol"
        else:
            try:
                result = mg.query(symbol, species="mouse", fields="ensembl", size=1)
                hits = result.get("hits", [])
                if hits and "ensembl" in hits[0]:
                    ensembl = hits[0]["ensembl"]
                    if isinstance(ensembl, list):
                        ensembl_id = str(ensembl[0]["gene"])
                    else:
                        ensembl_id = str(ensembl["gene"])
                    status = "mapped"
            except Exception as exc:  # Continue while retaining failed-query provenance.
                status = f"query_error:{type(exc).__name__}"

        records.append(
            {
                "gene_symbol": symbol,
                "ensembl_id": ensembl_id,
                "mapping_status": status,
            }
        )

    return pd.DataFrame.from_records(records)


def load_or_create_gene_map(
    gene_symbols: pd.Index,
    supplied_map: Path | None,
    output_path: Path,
) -> pd.DataFrame:
    if supplied_map is None:
        gene_map = query_mygene(gene_symbols)
    else:
        supplied_map = require_file(supplied_map, "Gene-symbol mapping CSV")
        gene_map = pd.read_csv(supplied_map, dtype=str).fillna("")
        required = {"gene_symbol", "ensembl_id"}
        missing = required - set(gene_map.columns)
        if missing:
            raise ValueError(
                "Gene mapping is missing required columns: " + ", ".join(sorted(missing))
            )
        if "mapping_status" not in gene_map:
            gene_map["mapping_status"] = np.where(
                gene_map["ensembl_id"].ne(""), "mapped_from_file", "not_found"
            )

    if gene_map["gene_symbol"].duplicated().any():
        raise ValueError("Gene mapping contains duplicate gene_symbol rows.")

    expected = set(gene_symbols.astype(str))
    observed = set(gene_map["gene_symbol"].astype(str))
    missing_symbols = sorted(expected - observed)
    if missing_symbols:
        raise ValueError(
            "Gene mapping does not contain all input symbols. Missing examples: "
            + ", ".join(missing_symbols[:10])
        )

    gene_map.to_csv(output_path, index=False)
    return gene_map


def apply_ensembl_ids(data: ad.AnnData, gene_map: pd.DataFrame) -> ad.AnnData:
    mapping = gene_map.set_index("gene_symbol")["ensembl_id"].astype(str)
    data.var["gene_symbol"] = data.var_names.astype(str)
    data.var["ensembl_id"] = data.var["gene_symbol"].map(mapping).fillna("")

    mapped = data.var["ensembl_id"].ne("")
    result = data[:, mapped].copy()
    result.var_names = result.var["ensembl_id"].astype(str)

    if result.var_names.has_duplicates:
        duplicated = result.var_names[result.var_names.duplicated()].unique()
        raise ValueError(
            "Multiple gene symbols mapped to the same Ensembl ID. Resolve the frozen "
            "mapping before MapMyCells. Duplicate examples: "
            + ", ".join(map(str, duplicated[:10]))
        )

    return result


def ensure_output_available(path: Path, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(
            f"Output already exists: {path}. Use --overwrite to replace it."
        )


def main() -> None:
    args = parse_args()

    input_dir = require_directory(args.input_dir, "CosMx input directory")
    run_metadata_path = require_file(args.run_metadata, "Run-metadata workbook")
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.n_features < 1:
        raise ValueError("--n-features must be at least 1.")
    if not 0 <= args.lower_quantile < args.upper_quantile <= 1:
        raise ValueError(
            "Filtering quantiles must satisfy 0 <= lower < upper <= 1."
        )

    final_output = output_dir / args.output_name
    prefilter_qc_path = output_dir / "cosmx_data_postscrub_prefilter_qc.xlsx"
    postfilter_qc_path = output_dir / "cosmx_data_postscrub_postfilter_qc.xlsx"
    gene_map_path = output_dir / "cosmx_gene_symbol_to_ensembl.csv"
    doublet_output = output_dir / "cosmx_data_all_postscrub.h5ad"
    preprocessing_output = output_dir / "cosmx_data_postscrub_ppfc.h5ad"
    provenance_path = output_dir / "cosmx_preprocessing_run_configuration.json"

    for path in (
        final_output,
        prefilter_qc_path,
        postfilter_qc_path,
        gene_map_path,
        doublet_output,
        preprocessing_output,
        provenance_path,
    ):
        ensure_output_available(path, args.overwrite)

    run_metadata = load_run_metadata(run_metadata_path)
    print(f"Pooling {run_metadata['Pair'].nunique()} CosMx pairs...")
    cosmx_data, source_files = pool_pairs(input_dir, run_metadata, args.n_features)
    n_cells_pooled, n_features_pooled = cosmx_data.shape

    print("Removing doublets...")
    cosmx_data = pp.exclude_doublets(
        cosmx_data,
        str(doublet_output),
        grouping="pair_age_plane",
        verbose=True,
    )
    n_cells_post_doublet = cosmx_data.n_obs

    print("Calculating prefilter QC summaries...")
    cosmx_data, qc_prefilter = pp.run_bulk_qc(
        cosmx_data,
        exp_cond="age",
        extra_groups=["pair", "plane", "age_plane", "pair_age_plane"],
        save_excel=False,
        vol_key=args.volume_key,
    )
    qc_prefilter.to_excel(prefilter_qc_path)

    print("Applying the original clustering-preprocessing filters...")
    cosmx_data = pp.run_default_cluster_pp(
        cosmx_data,
        quantiles=(args.lower_quantile, args.upper_quantile),
        save=str(preprocessing_output),
        vol_key=args.volume_key,
    )
    n_cells_post_filter = cosmx_data.n_obs

    if "raw_counts" not in cosmx_data.layers:
        raise KeyError(
            "run_default_cluster_pp did not create adata.layers['raw_counts']; "
            "raw counts are required for MapMyCells."
        )

    cosmx_data.layers["transformed_counts"] = cosmx_data.X.copy()
    cosmx_data.X = cosmx_data.layers["raw_counts"].copy()

    print("Calculating postfilter QC summaries from raw counts...")
    cosmx_data, qc_postfilter = pp.run_bulk_qc(
        cosmx_data,
        exp_cond="age",
        extra_groups=["pair", "plane", "age_plane", "pair_age_plane"],
        save_excel=False,
        vol_key=args.volume_key,
    )
    qc_postfilter.to_excel(postfilter_qc_path)

    # Restore transformed X before ID conversion, matching the original notebook,
    # then explicitly place raw counts in X for the final MapMyCells query object.
    cosmx_data.X = cosmx_data.layers["transformed_counts"].copy()

    print("Preparing a frozen mouse gene-symbol-to-Ensembl mapping...")
    gene_map = load_or_create_gene_map(
        cosmx_data.var_names,
        args.gene_map,
        gene_map_path,
    )
    cosmx_data = apply_ensembl_ids(cosmx_data, gene_map)
    n_features_ensembl = cosmx_data.n_vars

    if args.plane.lower() != "all":
        available_planes = set(cosmx_data.obs["plane"].astype(str))
        if args.plane not in available_planes:
            raise ValueError(
                f"Requested plane '{args.plane}' is absent. Available: "
                + ", ".join(sorted(available_planes))
            )
        cosmx_data = cosmx_data[cosmx_data.obs["plane"].astype(str) == args.plane].copy()

    cosmx_data.X = cosmx_data.layers["raw_counts"].copy()

    if cosmx_data.obs_names.has_duplicates:
        raise ValueError("Final AnnData contains duplicate cell identifiers.")
    if cosmx_data.var_names.has_duplicates:
        raise ValueError("Final AnnData contains duplicate Ensembl identifiers.")

    cosmx_data.uns["preprocessing"] = {
        "source": "SenNet CosMx mouse-brain collection",
        "run_metadata_file": run_metadata_path.name,
        "plane_subset": args.plane,
        "raw_counts_location": "X and layers/raw_counts",
        "transformed_counts_location": "layers/transformed_counts",
        "gene_identifier": "mouse Ensembl gene ID",
    }

    print(f"Writing final MapMyCells query object: {final_output}")
    cosmx_data.write_h5ad(final_output)

    provenance: dict[str, Any] = {
        "input_directory": str(input_dir),
        "run_metadata": str(run_metadata_path),
        "output_file": str(final_output),
        "source_files": source_files,
        "parameters": {
            "plane": args.plane,
            "n_features": args.n_features,
            "volume_key": args.volume_key,
            "filter_quantiles": [args.lower_quantile, args.upper_quantile],
            "gene_map_supplied": str(args.gene_map) if args.gene_map else None,
        },
        "dimensions": {
            "pooled_cells": n_cells_pooled,
            "pooled_features": n_features_pooled,
            "cells_after_doublet_removal": n_cells_post_doublet,
            "cells_after_filtering": n_cells_post_filter,
            "features_with_ensembl_ids": n_features_ensembl,
            "final_cells": cosmx_data.n_obs,
            "final_features": cosmx_data.n_vars,
        },
        "python_version": sys.version,
        "package_versions": {
            "anndata": package_version("anndata"),
            "scanpy": package_version("scanpy"),
            "pandas": package_version("pandas"),
            "numpy": package_version("numpy"),
            "mygene": package_version("mygene"),
            "kimlabspatial": package_version("kimlabspatial"),
        },
    }
    provenance_path.write_text(json.dumps(provenance, indent=2), encoding="utf-8")

    print("\nCosMx preprocessing completed successfully.")
    print(f"Final dimensions: {cosmx_data.n_obs:,} cells x {cosmx_data.n_vars:,} genes")
    print(f"Raw counts: adata.X and adata.layers['raw_counts']")
    print(f"Transformed counts: adata.layers['transformed_counts']")


if __name__ == "__main__":
    main()
